name = "MonteCarloIntegration"
uuid = "4886b29c-78c9-11e9-0a6e-41e1f4161f7b"
authors = ["Your Name <benditlikeranjan@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
